name: Build and deploy Python app to Azure Web App - immortal-journal-server

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        working-directory: ./backend/src
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt


      - name: Prepare artifact for deployment
        working-directory: ./backend/src
        run: |
          zip -r release.zip . -x "**/venv/**" "**/__pycache__/**" "**/.pytest_cache/**"


      - name: Upload artifact for deployment jobs
        working-directory: ./backend/src
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        working-directory: ./backend/src
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        working-directory: ./backend/src
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'immortal-journal-server'
          package: .
