name: Build and Deploy Vite App to Azure Web App

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Generate config.js with environment variables
        working-directory: ./frontend/public
        env:
          API_URL: ${{ secrets.API_URL }}
        run: |
          echo "window.__ENV__ = { API_URL: '$API_URL' };" > config.js

      - name: Build the app
        working-directory: ./frontend
        run: npm run build

      - name: Prepare deployment package
        working-directory: ./frontend
        run: |
          # Copy build output to root
          cp -r dist/* ./
          # No need to copy server.js since it's already at the root
          # Clean up unnecessary files
          rm -rf dist src public node_modules


      - name: Zip deployment package
        working-directory: ./frontend
        run: zip -r ../app.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: app.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-deploy
    environment:
      name: 'Development'
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: app

      - name: Unzip artifact for deployment
        run: unzip app.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'immortal-journal'
          package: .
